accuracy = {
    "epoch": [],
    "eval_accuracy_anchor": [],
    "eval_accuracy_pos": [],
    "eval_accuracy_neg": []
}

metrics = {
    "epoch": [],
    "train_quality_xentropy_anchor": [],
    "train_quality_xentropy_pos": [],
    "train_quality_xentropy_neg": [],
    "train_resonance_mse_anchor": [],
    "train_resonance_mse_pos": [],
    "train_resonance_mse_neg": [],
    "train_tension_mse_anchor": [],
    "train_tension_mse_pos": [],
    "train_tension_mse_neg": [],
    "train_longevity_cos_mse_anchor": [],
    "train_longevity_cos_mse_pos": [],
    "train_longevity_cos_mse_neg": [],
    "train_longevity_sin_mse_anchor": [],
    "train_longevity_sin_mse_pos": [],
    "train_longevity_sin_mse_neg": [],
    "eval_quality_xentropy_anchor": [],
    "eval_quality_xentropy_pos": [],
    "eval_quality_xentropy_neg": [],
    "eval_resonance_mse_anchor": [],
    "eval_resonance_mse_pos": [],
    "eval_resonance_mse_neg": [],
    "eval_tension_mse_anchor": [],
    "eval_tension_mse_pos": [],
    "eval_tension_mse_neg": [],
    "eval_longevity_cos_mse_anchor": [],
    "eval_longevity_cos_mse_pos": [],
    "eval_longevity_cos_mse_neg": [],
    "eval_longevity_sin_mse_anchor": [],
    "eval_longevity_sin_mse_pos": [],
    "eval_longevity_sin_mse_neg": [],
}